### PR TITLE
add Google Tag Manager to Zendesk pages

### PR DESCRIPTION
**Pull request by umarmughal824**
fixes https://github.com/mitodl/mitxpro/issues/2060

#### Screenshots
**Now**

Screenshot 2021-01-20 at 20 19 06

**Before**

Screenshot 2021-01-20 at 20 19 15

### CODE REVIEW

**Comment by briangrossman** [comment]
Someone else will need to do a full review testing in in the environment, but here's some questions / notes:
- It looks like you're using the code `GTM-MT2XTXB` in your <noscript><iframe> line, but `APIKEYS.GTM_TRACKING_ID` in the javascript function. Should they be the same? And where is `APIKEYS.GTM_TRACKING_ID` defined? We want to make sure it gets picked up.
- During testing, we'll need to confirm that data is getting logged properly
- I think I'm the one that will need to launch this when it's ready.

**Comment by umarmughal824** [comment]
@briangrossman thanks for pointing it out. I might have not noticed it. It should be 'GTM-MT2XTXB'. Regarding testing, it could be tested on RC or if someone has that zendesk tool setup locally.

**Comment by briangrossman** [comment]
@umarmughal824 Thanks.

Once the code review is completed (looks like you requested Asad), I'll work with someone from the marketing team to make sure the data is being tracked properly in Google Tag Manager.

**Comment by briangrossman** [comment]
FYI: You can use this to check if the tags are firing: https://chrome.google.com/webstore/detail/tag-assistant-by-google/kejbdjndbnbjgmefkgdddjlbokphdefk?hl=en

**Comment by umarmughal824** [comment]
@briangrossman I have verified the google tag and have attached the working screenshots of it. Now, it should be easy to review.

**Comment by briangrossman** [comment]
@umarmughal824 
From my perspective, this looks good. I'm not able to test on a local build, but I checked your code against the [Google Tag Manager instructions](https://developers.google.com/tag-manager/quickstart) and double-checked the code you're using: `GTM-MT2XTXB`. The fact that it's working and returning events is good enough for me. 

Merge it and I'll launch it.

Thanks!

👍

**Pull request merged**
