### PR TITLE
update copyright date

### PR DESCRIPTION
**Pull request by umarmughal824**
update copyright date

#### Related Tickets
fixes https://github.com/mitodl/mitxpro/issues/2101

#### Screenshots
Screenshot 2021-02-02 at 16 26 34

### CODE REVIEW

**Comment by HamzaIbnFarooq** [comment]
@umarmughal824 the PR looks good, but have you deployed it somewhere for testing?

**Comment by umarmughal824** [comment]
@HamzaIbnFarooq this screenshots is attached with you from the deployed instance

**Review by HamzaIbnFarooq — APPROVED** [review]
The code and screenshots look great.

**Comment by briangrossman** [comment]
This is live and looks good.

**Pull request merged**
