### PR TITLE
Improve readability of Support Center (Zendesk) pages

### PR DESCRIPTION
**Pull request by umarmughal824**
fixes https://github.com/mitodl/mitxpro/issues/2011
Improve readability of Support Center (Zendesk) pages

### CODE REVIEW

**Comment by asadiqbal08** [comment]
@umarmughal824 changes seems good to me but would you like to attach some screenshots here for getting approval by @briangrossman over design ?

**Review by asadiqbal08 — APPROVED** [review]

**Comment by umarmughal824** [comment]
@asadiqbal08 I don't have the Zendesk tools configured locally after facing issues in a local installation. so I had discussed it with @pdpinch who suggested that it would be tested on RC, just put up the PR and code review would be enough or it will be reviewed by @asadiqbal08. So, I merged on behalf of that.

**Comment by asadiqbal08** [comment]
@pdpinch , I jumped over the [odl-zendesk](https://odl.zendesk.com/knowledge/lists/default/1/1?brand_id=360002315832) instance for xPro ( that I worked over it a year back). It seems me, my account is not authorized now for publishing a .zip theme there. 

However, It is an easy process to make a theme live there -- [youtube-ref](https://www.youtube.com/watch?v=kD2ZwxeKhuI)

[Importing a theme](https://support.zendesk.com/hc/en-us/articles/115012794168)

**Comment by asadiqbal08** [comment]
I would suggest, It would be nice if we create a story for tracking this deployment & testing this feature over RC.

**Comment by briangrossman** [comment]
@asadiqbal08 : I looks like I have the permissions necessary to publish a theme. 

Is it possible for you to get me the .zip?

**Pull request merged**
